"""add task submission items

Revision ID: 032925c9a944
Revises: 950bb24314f4
Create Date: 2026-07-24 04:12:22.748605

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '032925c9a944'
down_revision: str | None = '950bb24314f4'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_submission_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('photo_key', sa.String(length=255), nullable=True),
    sa.Column('video_key', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['task_dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submission_items_dispatch_id'), 'task_submission_items', ['dispatch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_submission_items_dispatch_id'), table_name='task_submission_items')
    op.drop_table('task_submission_items')
    # ### end Alembic commands ###
