"""make task deadline_at nullable

Revision ID: 0658fa65f305
Revises: cdc35e170236
Create Date: 2026-07-23 22:25:03.265117

"""
from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0658fa65f305'
down_revision: str | None = 'cdc35e170236'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
