"""add team point adjustments

Revision ID: 43d07c9f77c9
Revises: 1aaea6cca242
Create Date: 2026-07-26 06:40:23.210552

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '43d07c9f77c9'
down_revision: str | None = '1aaea6cca242'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_point_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_point_adjustments_team_id'), 'team_point_adjustments', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_point_adjustments_team_id'), table_name='team_point_adjustments')
    op.drop_table('team_point_adjustments')
    # ### end Alembic commands ###
