"""create users and applications tables

Revision ID: 5b94d643c5d9
Revises: 0001
Create Date: 2026-07-10 11:32:02.111883

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5b94d643c5d9'
down_revision: str | None = '0001'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_document', 'pending_ocr', 'document_flagged', 'pending_video', 'pending_moderation', 'reupload_requested', 'approved', 'rejected', name='applicationstatus', native_enum=False, length=30), server_default='draft', nullable=False),
    sa.Column('pdn_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_photo_key', sa.String(length=255), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('video_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_applications_phone'), 'applications', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_phone'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
