"""add selection stage and blogger flag

Revision ID: 606d442892e5
Revises: 9a125bf14fcb
Create Date: 2026-07-23 13:01:35.075276

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '606d442892e5'
down_revision: str | None = '9a125bf14fcb'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('selection_stage', sa.Enum('voting', 'eliminated_stage1', 'winner', 'eliminated_stage2', name='selectionstage', native_enum=False, length=30), nullable=True))
    op.add_column('applications', sa.Column('is_blogger', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_blogger')
    op.drop_column('applications', 'selection_stage')
    # ### end Alembic commands ###
