"""add task trigger scheduling

Revision ID: 950bb24314f4
Revises: 0658fa65f305
Create Date: 2026-07-23 23:31:14.002358

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '950bb24314f4'
down_revision: str | None = '0658fa65f305'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('trigger_task_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('trigger_delay_minutes', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'send_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'tasks', 'tasks', ['trigger_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'send_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('tasks', 'trigger_delay_minutes')
    op.drop_column('tasks', 'trigger_task_id')
    # ### end Alembic commands ###
