"""add task deadline reminder flag

Revision ID: 9d4429c53d22
Revises: 032925c9a944
Create Date: 2026-07-24 17:41:56.448613

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9d4429c53d22'
down_revision: str | None = '032925c9a944'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_dispatches', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_dispatches', 'reminder_sent')
    # ### end Alembic commands ###
