"""add document verification fields to applications

Revision ID: afbb895ada13
Revises: 5b94d643c5d9
Create Date: 2026-07-10 12:33:32.078830

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'afbb895ada13'
down_revision: str | None = '5b94d643c5d9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('document_iin', sa.String(length=12), nullable=True))
    op.add_column('applications', sa.Column('document_expiry_date', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('ocr_raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('verification_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_applications_document_iin'), 'applications', ['document_iin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_document_iin'), table_name='applications')
    op.drop_column('applications', 'verification_flags')
    op.drop_column('applications', 'ocr_raw_data')
    op.drop_column('applications', 'document_expiry_date')
    op.drop_column('applications', 'document_iin')
    # ### end Alembic commands ###
