"""add user language and application participant_number

Revision ID: c2c43329bb2b
Revises: 58d746f55db3
Create Date: 2026-07-17 12:40:53.912993

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c2c43329bb2b'
down_revision: str | None = '58d746f55db3'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('participant_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'applications', ['participant_number'])
    op.add_column('users', sa.Column('language', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_column('applications', 'participant_number')
    # ### end Alembic commands ###
