"""add teams, tasks, task_dispatches

Revision ID: cdc35e170236
Revises: 606d442892e5
Create Date: 2026-07-23 13:25:48.798184

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cdc35e170236'
down_revision: str | None = '606d442892e5'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_daily', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('penalty_points', sa.Integer(), server_default='2', nullable=False),
    sa.Column('dispatched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('penalties_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('penalty_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'team_id')
    )
    op.create_index(op.f('ix_task_dispatches_task_id'), 'task_dispatches', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_dispatches_team_id'), 'task_dispatches', ['team_id'], unique=False)
    op.add_column('applications', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'team_id')
    op.drop_index(op.f('ix_task_dispatches_team_id'), table_name='task_dispatches')
    op.drop_index(op.f('ix_task_dispatches_task_id'), table_name='task_dispatches')
    op.drop_table('task_dispatches')
    op.drop_table('teams')
    op.drop_table('tasks')
    # ### end Alembic commands ###
